spring:
  application:
    name: gateway
  cloud:
    gateway:
      filter:
        secure-headers:
          enabled: true
      server:
        webflux:
          discovery:
            locator:
              enabled: false

# Server configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.ems.gateway: DEBUG
