spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          filter:
            secure-headers:
              enabled: true
          routes:
            # Public routes - no authentication required
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
                
            - id: gateway-health
              uri: http://localhost:8080
              predicates:
                - Path=/api/gateway/**
                
            # Routes requiring authentication
            - id: ems-legacy
              uri: http://localhost:8081
              predicates:
                - Path=/ems/legacy/login
              filters:
                - RewritePath=/ems/legacy/login, /ems/login
                - name: RoleBasedAuthorizationFilter
                  args:
                    allowedRoles: ADMIN,MANAGER,EMPLOYEE 
          discovery:
            locator:
              enabled: false

# Server configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.ems.gateway: DEBUG
