version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      USER_NAME: ${USER_NAME}
      PASSWORD: ${PASSWORD}
      DB_CONTAINER_NAME: ${DB_CONTAINER_NAME}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/dataGcp.json
    volumes:
       - ./gcp/dataGcp.json:/app/dataGcp.json:ro
    command: >
      sh -c "
      echo 'Esperando MySQL...' &&
      until nc -z mysql 3306; do sleep 2; done &&
      java -jar app.jar
      "
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  mysql_data:
