apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems-backend-db-pvc
  namespace: ems
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems-legacy-db-pvc
  namespace: ems
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems-legacy-logs-pvc
  namespace: ems
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
